<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP9Vnzqb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP9Vnzqb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP9Vnzqb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP9Vnzqb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP9Vnzqb\App_KernelDevDebugContainer([
    'container.build_hash' => 'P9Vnzqb',
    'container.build_id' => '07690e82',
    'container.build_time' => 1647070952,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP9Vnzqb');
